## Week 11 Assignment - W200 Python Fundamentals for Data Science, UC Berkeley MIDS

Write code in this Jupyter Notebook to solve the following problems. Please upload this **Notebook** with your solutions to your GitHub repository in your SUBMISSIONS/week_11 folder by 11:59PM PST the night before class.

This homework assignment is Week 11 which corresponds to the Unit #10 async. If you turn-in anything on ISVC please do so under the Week 11 Assignment category. (Apologies for the confusion)

## Objectives

- Demonstrate use of map and filter commands
- Practice list comprehensions and lambda functions
- Understand different ways to manipulate and perform calculations on Numpy arrays including:
- Changing datatypes, getting the max values in each column and row, calculating the mean of a matrix
- Matrix value comparisons and slicing of values

## 1. List, Mapping, Filtering, and Reducing Comprehensions

**A.** Write a function that doubles any number (integer or floating type values), reverses the content if it is a string, and does nothing if it is another kind of value.

Use that function in a **list comprehension** and apply it to the below list of data.

Example of the first two entries:
```
['cinesra', 10, ...]
```

In [2]:
fix_me = ['arsenic', 5, 'ball', 2, 47, 123, 
          'comprehensions', 'list', 5.5, 
          8343.23, 'shishkabob', True]

In [3]:
# Put the function here
def function_1(x):
    if type(x) is int or type(x) is float:
        return x * 2
    elif type(x) is str:
        return x[::-1]
    else:
        return x

In [4]:
# Put the list comprehension (which calls your function above) here 
[function_1(x) for x in fix_me]

['cinesra',
 10,
 'llab',
 4,
 94,
 246,
 'snoisneherpmoc',
 'tsil',
 11.0,
 16686.46,
 'bobakhsihs',
 True]

**B.** Now apply your function made in **A** above using a **map**.

In [5]:
list(map(function_1, fix_me))

['cinesra',
 10,
 'llab',
 4,
 94,
 246,
 'snoisneherpmoc',
 'tsil',
 11.0,
 16686.46,
 'bobakhsihs',
 True]

**C.** Repeat step **B**, except use **filter** to remove any number values that are less than 5 after your map.  You may use a separate function to filter (or could do it with one statement).

In [6]:
def filter_5(x):
    if (type(x) is float or type(x) is int) and (x < 5):
        return False
    else:
            return True

list(filter(filter_5, map(function_1, fix_me)))

['cinesra',
 10,
 'llab',
 94,
 246,
 'snoisneherpmoc',
 'tsil',
 11.0,
 16686.46,
 'bobakhsihs',
 True]

**D.** Update your solution to **C** to use **lambda** expressions instead of functions for both the map and the filter. This needs to be done in one statement. If you are having trouble converting your functions to lambda functions, try to understand how the sample code below is working:
```python
y = lambda symbol: 'X' if symbol==True else 'O' if symbol==False else ' '
```
Hint: It might be helpful to test the map part and the filter part as separate statements and then combine them into one statement for the final answer.

In [7]:
list(filter(lambda x: not (((type(x) is float) or (type(x) is int)) and (x < 5)), map(function_1, fix_me)))

['cinesra',
 10,
 'llab',
 94,
 246,
 'snoisneherpmoc',
 'tsil',
 11.0,
 16686.46,
 'bobakhsihs',
 True]

# 2. Generating Random Data and Filtering That Data

In this next section, we will work with NumPy. Please run your the cell below to set your random seed. (This makes the 'randomness' of the array the same for everyone)

In [8]:
# Do NOT change this code!
import numpy as np
np.random.seed(25)
ar = np.random.randn(1000)

Now we will start playing around with this data. This part of the assignment will prompt you to follow a series of steps and output your answers. 

For the first number of these steps, the problem asks you to modify the dataset and use the new dataset in the next step.  For these steps, you will use the `ar` value that we created above, and after each step, you should set `ar` to be the new `ar` value. Using this process, you will update your dataset each step of the way. The later steps do not ask for this. It sounds confusing but there is a note on what to do on each question.  

Please run the cell below as the first step:

**Multiply all values by 100 and assign this back to ar**

So your answer will be the following:

In [9]:
# Do NOT change this code!
ar = ar * 100
ar

array([ 2.28273090e+01,  1.02689030e+02, -8.39584849e+01, -5.91181518e+01,
       -9.56888297e+01, -2.22325694e+01, -6.19915108e+01,  1.83790458e+02,
       -2.05323076e+02,  8.68583052e+01, -9.20734440e+01, -2.32311864e+01,
        2.15295690e+02, -1.33466147e+02,  7.63796505e+00, -1.24608928e+02,
        1.20227231e+02, -1.04994158e+02,  1.05661011e+02, -4.19677671e+01,
        2.29484234e+02, -2.59448738e+02,  2.82275640e+02,  6.80888923e+01,
       -1.57769345e+02, -1.97625359e+02,  5.33339823e+01, -2.90869712e+01,
       -5.13519669e+01,  1.98262608e+02,  2.26001050e+01, -1.83990496e+02,
        1.60767083e+02,  3.88291936e+01,  3.99732064e+01,  4.05476600e+01,
        2.17001772e+01, -6.33439103e+01,  2.46621529e+01, -1.93954552e+02,
        1.14059633e+01, -1.88534140e+02,  2.43080482e+01, -7.05480672e+01,
        3.64627615e+01, -5.02952163e+01, -2.25751546e+01, -5.65537733e+01,
        1.03395013e+01,  2.01840842e+02,  1.09424827e+02,  1.66243440e+02,
       -6.27453481e+01,  

*the first 3 values should be*
```
2.28273090e+01,   1.02689030e+02,  -8.39584849e+01,
```

**A.** Now convert the `ar` matrix into a matrix of 8-bit integers and assign this back to `ar`.

In [10]:
ar = np.int8(ar)
print("Data type:", ar.dtype)
print("First three values:", ar[0:3])
print("Length:", ar.size)

Data type: int8
First three values: [ 22 102 -83]
Length: 1000


The first 3 values should be:
```
 22,  102,  -83,
```
And the length should be 1000.

**B.** Reshape the array into a set of five columns with 200 rows. Replace the original `ar` array with this new matrix.

In [12]:
ar = ar.reshape(200, 5)
ar

array([[  22,  102,  -83,  -59,  -95],
       [ -22,  -61,  -73,   51,   86],
       [ -92,  -23,  -41,  123,    7],
       [-124,  120, -104,  105,  -41],
       [ -27,   -3,   26,   68,   99],
       [  59,   53,  -29,  -51,  -58],
       [  22,   73,  -96,   38,   39],
       [  40,   21,  -63,   24,   63],
       [  11,   68,   24,  -70,   36],
       [ -50,  -22,  -56,   10,  -55],
       [ 109,  -90,  -62,  -94,  117],
       [ -37,  -54,   28,  -20,  118],
       [  72,  -22,   94,   31, -116],
       [  31,   47,   57,   50,  -62],
       [ -34,   50,   76,  112,   16],
       [ -96,   49,  -55,   -8,  -60],
       [  -6,  -85,   42,  -27,  119],
       [  -9,   83,  -78,  104,  -64],
       [  67,   -9,  121,   49, -114],
       [ -53,  -91,  -21,   19,  -32],
       [  84,   76,   44,   43,  102],
       [ -58,    4,   56, -114,    0],
       [ -29,   23,   67,  122,  -60],
       [ -16,  -65,  -19,   17,    3],
       [-126,  -53,   52,   38,  -76],
       [  -5,  -24,   20,

**C.** Now that `ar` is a matrix, get the maximum and minimum values from the matrix both row-wise and column-wise. Be sure to remember how many total values you should be outputting - in the first cell should be one value for every row; in the second cell should be one value for each column. Do **NOT** assign this to `ar`, just show the values.

In [13]:
print(ar.max(axis=1))
print(ar.min(axis=1))

[102  86 123 120  99  59  73  63  68  10 117 118  94  57 112  49 119 104
 121  19 102  56 122  17  52  20  54 101  43 -16 112  93  64  59  62  92
  63 101  90 120 111  97  64  40  98 106  96  80  71  59  73  24  57  68
  65 120 117  94 102  28   2  93  66  58 111  83 126  17 111 111  46  70
 121 124  89  98  43  98 106  94 100  78  78  45  71  53   6  86  57 119
 125  37  74  72 105  61 116  80 123  41 117  69  71 110 105  91  33 111
 125 114 121  44 124 116  28  89  -1  67 124 117 126  45  93 106 100  97
 113  64 112  74 118  82 103   1  57 123  50 126 119  24   1 119  80 109
 126  85 110  73 115  52 115  62  54  46 102 107 106  68  79  98  98  78
  68  58  88  86  52  93  75  81 126 104  94  -9 123 118  65 121  79  18
  22  81  48 108 119 116 118  98 121  36 125 -30  87  11  18 114  93  95
  -2 127]
[ -95  -73  -92 -124  -27  -58  -96  -63  -70  -56  -94  -54 -116  -62
  -34  -96  -85  -78 -114  -91   43 -114  -60  -65 -126  -30  -77 -115
 -109  -88 -114  -85  -90 -126  -52  -84 -128

In [14]:
print(ar.max(axis=0))
print(ar.min(axis = 0))

[123 125 126 126 127]
[-127 -127 -127 -128 -127]


**D.** Now that we have gotten the minimum and maximum values for the rows and columns, get the mean of the entire matrix. This should be one specific value. Do **NOT** assign this to `ar`, just show the value.

In [15]:
ar.mean()

-0.791

**E.** What is the total number of values in the `ar` matrix that are less than the mean calculated in **D** above? Do **NOT** assign this to `ar`, just show the value.

In [16]:
ar[ar < ar.mean()].size

494

**F.** What are the total number of values in *each row* that are greater than the mean calculated in **D** above? (Remember, if we are doing a row-oriented comparison, how many numbers should be in our output array?) Do **NOT** assign this to `ar`, just show the values.

In [17]:
print([row[row > ar.mean()].size for row in ar])

[2, 2, 2, 2, 3, 2, 4, 4, 4, 1, 2, 2, 3, 4, 4, 1, 2, 2, 3, 1, 5, 3, 3, 2, 2, 2, 2, 2, 2, 0, 3, 2, 3, 1, 4, 2, 1, 2, 3, 3, 2, 3, 3, 1, 2, 1, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 4, 3, 2, 2, 1, 5, 2, 4, 3, 3, 3, 1, 2, 4, 1, 4, 4, 3, 3, 1, 3, 4, 3, 4, 2, 3, 3, 4, 2, 2, 1, 3, 1, 2, 4, 1, 1, 4, 2, 4, 2, 2, 2, 1, 2, 5, 4, 3, 4, 5, 2, 4, 4, 2, 4, 3, 3, 4, 1, 2, 0, 3, 2, 4, 3, 3, 3, 2, 4, 2, 3, 1, 2, 4, 4, 2, 4, 1, 1, 3, 4, 2, 3, 1, 1, 2, 2, 4, 2, 2, 5, 2, 4, 1, 2, 3, 2, 2, 4, 1, 3, 1, 4, 2, 2, 3, 1, 2, 3, 3, 3, 4, 3, 2, 3, 3, 3, 0, 3, 3, 1, 2, 3, 1, 1, 4, 3, 5, 3, 4, 2, 1, 3, 2, 2, 0, 1, 1, 3, 3, 3, 3, 0, 5]


**G.** How many zeros are in the matrix that we have? Do **NOT** assign this to `ar`, just show the value.

In [18]:
ar[ar == 0].size

8

**H.** Lastly, sum all the values that are: 
- (Greater than 100) and (less than 5 and greater than or equal to -20). 

Do **NOT** assign this to `ar`, just show the value.

In [19]:
ar[(ar > 100)].sum() + ar[((ar < 5) & (ar >= -20))].sum()

9044